[build]
  command = "echo 'No build command needed for static site + functions'"
  publish = "public"
  functions = "netlify/functions"

[functions]
  python_version = "3.9"
  # Netlify 빌드 오류 메시지에 제시된 'Valid syntax'에 따라 빈 테이블로 설정합니다.
  # Netlify가 파이썬 버전을 자동으로 감지하거나 기본값을 사용할 수 있습니다.
